"""Cue-equivariant symmetric contraction implemented with Flax.

This module bridges the Torch/cuEquivariance symmetric contraction operator used
throughout MACE with a Flax/JAX implementation.  It exposes a drop-in compatible
``SymmetricContraction`` layer that:

* Reconstructs the exact equivariant polynomial descriptor used by the
  reference Torch implementation.
* Handles both reduced and full Clebsch–Gordan bases.
* Allows the caller to pick a specific element embedding at apply time via an
  ``indices`` argument, mirroring the original torch-scatter based interfaces.
* Provides import utilities so state dictionaries from Torch can be moved to the
  JAX module without numerical drift.

The implementations in this file are intentionally verbose: each helper carries
docstrings describing the slightly idiosyncratic layout conversions required by
cuEquivariance and e3nn, and the import code documents the exact ordering of
weights that is expected during the conversion.
"""

from __future__ import annotations

import logging

import cuequivariance_jax as cuex
import jax
import jax.numpy as jnp
import numpy as np
from flax import nnx

import cuequivariance as cue
from cuequivariance.group_theory.experimental.mace.symmetric_contractions import (
    symmetric_contraction as cue_mace_symmetric_contraction,
)
from mace_model.core.modules.native_symmetric_weights import (
    convert_native_symmetric_weights,
)
from mace_model.jax.adapters.e3nn import Irreps
from mace_model.jax.adapters.nnx.torch import (
    _resolve_scope,
    nxx_auto_import_from_torch,
    nxx_register_import_mapper,
)
from mace_model.jax.nnx_config import ConfigVar
from mace_model.jax.nnx_utils import state_to_pure_dict
from mace_model.jax.tools.dtype import default_dtype

from .utility import ir_mul_to_mul_ir


@nxx_auto_import_from_torch(allow_missing_mapper=True)
class SymmetricContraction(nnx.Module):
    """Symmetric contraction layer evaluated with cuequivariance-jax.

    Parameters
    ----------
    irreps_in:
        e3nn irreps describing the incoming node features.  All entries must
        share a common multiplicity.
    irreps_out:
        Target irreps produced by the contraction.  The multiplicity must match
        that of ``irreps_in``.
    correlation:
        Maximum correlation order (degree) used by the symmetric contraction.
        The operator internally builds all degrees in ``[1, correlation]``.
    num_elements:
        Number of distinct chemical elements represented in the embedding table.
        The ``indices`` argument selects one of these entries per node.
    use_reduced_cg:
        When ``True`` (default) the operator stores weights in the reduced
        Clebsch–Gordan basis generated by cuEquivariance.  Setting ``False``
        expands the basis to the original dense CG space.
    input_layout:
        Expected ordering of the feature tensor passed to :meth:`__call__`.  The
        default ``'mul_ir'`` matches e3nn; ``'ir_mul'`` accepts the cuEquivariance
        layout instead.

    Notes
    -----
    The class stores the cuEquivariance descriptor built from
    ``experimental.mace.symmetric_contractions`` so that the exact polynomial
    used in Torch is evaluated in JAX.  All layout conversions are handled inside
    the module; callers only need to observe the ``input_layout`` argument.
    """

    irreps_in: Irreps
    irreps_out: Irreps
    correlation: int
    num_elements: int
    use_reduced_cg: bool = True
    input_layout: str = "mul_ir"
    output_layout: str = "mul_ir"
    group: object = cue.O3

    def __init__(
        self,
        irreps_in: Irreps,
        irreps_out: Irreps,
        correlation: int,
        num_elements: int,
        use_reduced_cg: bool = True,
        input_layout: str = "mul_ir",
        output_layout: str = "mul_ir",
        group: object = cue.O3,
        *,
        rngs: nnx.Rngs | None = None,
    ) -> None:
        """Validate configuration and construct the cuEquivariance descriptor.

        The routine performs a number of sanity checks that mirror the Torch
        implementation, computes the projection matrix when full CG weights are
        requested, and creates the cached descriptor that is reused on every
        forward pass.
        """
        self.irreps_in = irreps_in
        self.irreps_out = irreps_out
        self.correlation = correlation
        self.num_elements = num_elements
        self.use_reduced_cg = use_reduced_cg
        self.input_layout = input_layout
        self.output_layout = output_layout
        self.group = group

        if self.correlation <= 0:
            raise ValueError("correlation must be a positive integer")
        if self.num_elements <= 0:
            raise ValueError("num_elements must be positive")
        if self.input_layout not in {"mul_ir", "ir_mul"}:
            raise ValueError(
                "input_layout must be either 'mul_ir' or 'ir_mul'; "
                f"got {self.input_layout!r}"
            )
        if self.output_layout not in {"mul_ir", "ir_mul"}:
            raise ValueError(
                "output_layout must be either 'mul_ir' or 'ir_mul'; "
                f"got {self.output_layout!r}"
            )

        input_layout_code = 0 if self.input_layout == "mul_ir" else 1
        output_layout_code = 0 if self.output_layout == "mul_ir" else 1
        self.input_layout_config = ConfigVar(
            jnp.asarray(input_layout_code, dtype=jnp.int32),
            is_mutable=False,
        )
        self.output_layout_config = ConfigVar(
            jnp.asarray(output_layout_code, dtype=jnp.int32),
            is_mutable=False,
        )

        irreps_in_o3 = Irreps(self.irreps_in)
        irreps_out_o3 = Irreps(self.irreps_out)
        self.irreps_in_o3_str = str(irreps_in_o3)
        self.irreps_out_o3_str = str(irreps_out_o3)

        muls_in = {mul for mul, _ in irreps_in_o3}
        muls_out = {mul for mul, _ in irreps_out_o3}
        if len(muls_in) != 1 or len(muls_out) != 1 or muls_in != muls_out:
            raise ValueError(
                "SymmetricContraction requires all input/output irreps to share the same multiplicity"
            )
        self.mul = next(iter(muls_in))

        self.irreps_in_cue = cue.Irreps(self.group, irreps_in_o3)
        self.irreps_out_cue = cue.Irreps(self.group, irreps_out_o3)
        self.feature_dim = sum(ir.dim for _, ir in irreps_in_o3)
        self.irreps_in_cue_base = self.irreps_in_cue.set_mul(1)
        self.irreps_out_dim = irreps_out_o3.dim

        degrees = tuple(range(1, self.correlation + 1))
        descriptor, projection = cue_mace_symmetric_contraction(
            self.irreps_in_cue,
            self.irreps_out_cue,
            degrees,
        )
        self.descriptor = descriptor
        self.weight_irreps = descriptor.inputs[0].irreps
        self.weight_numel = self.weight_irreps.dim

        if self.use_reduced_cg:
            self.projection = None
            if projection is not None:
                self.weight_basis_dim = int(np.asarray(projection).shape[1])
            else:
                self.weight_basis_dim = self.weight_numel // self.mul
        else:
            self.projection = jnp.asarray(projection)
            self.weight_basis_dim = self.projection.shape[0]

        self.weight_param_shape = (self.num_elements, self.weight_basis_dim, self.mul)
        if rngs is None:
            raise ValueError("rngs is required to initialize SymmetricContraction")
        self.weight = nnx.Param(
            jax.random.normal(
                rngs(),
                self.weight_param_shape,
                dtype=default_dtype(),
            )
        )

    def _weight_param(self) -> jnp.ndarray:
        """Return the learnable basis weights initialised with Gaussian noise.

        Returns
        -------
        jnp.ndarray
            Parameter tensor of shape ``(num_elements, basis_dim, mul)`` stored
            in the current Flax variable collection.
        """
        return self.weight

    def _ensure_mul_ir_layout(self, x: jnp.ndarray) -> jnp.ndarray:
        """Convert inputs to mul_ir layout if needed.

        Parameters
        ----------
        x:
            Feature tensor with either ``mul_ir`` or ``ir_mul`` ordering.

        Returns
        -------
        jnp.ndarray
            Tensor guaranteed to be in ``mul_ir`` layout.
        """
        if self.input_layout == "ir_mul":
            return self._convert_ir_mul_to_mul_ir(x)
        return x

    def _features_to_rep_ir_mul(
        self, x: jnp.ndarray, dtype: jnp.dtype
    ) -> cuex.RepArray:
        """Pack ir_mul features into cue RepArray segments without layout conversion."""
        segments: list[jnp.ndarray] = []
        offset = 0
        for mul_ir in self.irreps_in_cue_base:
            width = mul_ir.ir.dim
            seg = x[:, offset : offset + width, :]
            if seg.shape[1] != width:
                raise ValueError("Input feature dimension mismatch with irreps.")
            segments.append(seg)
            offset += width

        if offset != x.shape[1]:
            raise ValueError("Input feature dimension mismatch with irreps.")

        return cuex.from_segments(
            self.irreps_in_cue,
            segments,
            (x.shape[0], self.mul),
            cue.ir_mul,
            dtype=dtype,
        )

    def _project_basis_weights(
        self, basis_weights: jnp.ndarray, dtype: jnp.dtype
    ) -> jnp.ndarray:
        """Project basis weights to the full Clebsch–Gordan space.

        Parameters
        ----------
        basis_weights:
            Learned weights in the reduced space.
        dtype:
            Desired data type of the projected weights.

        Returns
        -------
        jnp.ndarray
            Weights expressed in the basis expected by the descriptor.
        """
        if self.projection is None:
            return basis_weights.astype(dtype)
        projection = jnp.asarray(self.projection, dtype=dtype)
        return jnp.einsum("zau,ab->zbu", basis_weights.astype(dtype), projection)

    def _weight_rep_from_indices(
        self,
        indices: jnp.ndarray,
        dtype: jnp.dtype,
    ) -> cuex.RepArray:
        """Select element weights and wrap them as a cue RepArray.

        Parameters
        ----------
        indices:
            Int tensor of shape ``(batch,)`` or mixing matrix of shape
            ``(batch, num_elements)`` selecting the element embedding.
        dtype:
            Desired numeric type.

        Returns
        -------
        cuex.RepArray
            Representation-aware view of the selected weights.
        """
        basis_weights = self._weight_param()
        projected = self._project_basis_weights(basis_weights, dtype)
        weight_flat = projected.reshape(self.num_elements, self.weight_numel)
        selected = _select_weights(
            weight_flat,
            indices,
            dtype=dtype,
            num_elements=self.num_elements,
        )
        return cuex.RepArray(self.weight_irreps, selected, cue.ir_mul)

    def __call__(
        self,
        x: jnp.ndarray,
        indices: jnp.ndarray,
    ) -> jnp.ndarray:
        """Apply the symmetric contraction and return mul_ir-ordered features.

        Parameters
        ----------
        x:
            Either a flattened ``(batch, mul * feature_dim)`` array or the
            explicit ``(batch, mul, feature_dim)`` view containing the node
            features ready for contraction.
        indices:
            Element identifiers or mixing matrices selecting the weight slice.

        Returns
        -------
        jnp.ndarray
            Contracted features in ``mul_ir`` layout matching ``irreps_out``.
        """
        array = jnp.asarray(x)
        dtype = array.dtype

        if array.ndim == 2:
            expected = self.mul * self.feature_dim
            if array.shape[1] != expected:
                raise ValueError(
                    "Flattened features must have size "
                    f"{expected}; received {array.shape[1]}"
                )
            if self.input_layout == "mul_ir":
                array = array.reshape(array.shape[0], self.mul, self.feature_dim)
            elif self.input_layout == "ir_mul":
                array = array.reshape(array.shape[0], self.feature_dim, self.mul)
            else:
                raise ValueError(f"Unsupported input_layout {self.input_layout!r}")
        elif array.ndim != 3:
            raise ValueError(
                "SymmetricContraction expects inputs with rank 2 or 3; "
                f"got rank {array.ndim}"
            )

        weight_rep = self._weight_rep_from_indices(indices, dtype)
        if self.input_layout == "ir_mul":
            _validate_features_ir_mul(array, self.mul, self.feature_dim)
            x_rep = self._features_to_rep_ir_mul(array, dtype)
        else:
            array = self._ensure_mul_ir_layout(array)
            _validate_features(array, self.mul, self.feature_dim)
            x_rep = self._features_to_rep(array, dtype)

        out_rep = cuex.equivariant_polynomial(
            self.descriptor,
            [weight_rep, x_rep],
            math_dtype=dtype,
            method="naive",
        )

        out_ir_mul = out_rep.change_layout(cue.ir_mul).array

        if self.output_layout == "ir_mul":
            return out_ir_mul
        return ir_mul_to_mul_ir(
            out_ir_mul,
            Irreps(self.irreps_out_o3_str),
        )

    def _features_to_rep(self, x: jnp.ndarray, dtype: jnp.dtype) -> cuex.RepArray:
        """Pack mul_ir features into cue RepArray segments.

        Parameters
        ----------
        x:
            Feature tensor in mul_ir layout of shape ``(batch, mul, feature_dim)``.
        dtype:
            Desired dtype of the resulting representation array.

        Returns
        -------
        cuex.RepArray
            Features understood by cuEquivariance, segmented per irrep.
        """
        segments: list[jnp.ndarray] = []
        offset = 0
        for mul_ir in self.irreps_in_cue_base:
            width = mul_ir.ir.dim
            seg = x[:, :, offset : offset + width]
            if seg.shape[-1] != width:
                raise ValueError("Input feature dimension mismatch with irreps.")
            segments.append(jnp.swapaxes(seg, -2, -1))
            offset += width

        return cuex.from_segments(
            self.irreps_in_cue,
            segments,
            (x.shape[0], self.mul),
            cue.ir_mul,
            dtype=dtype,
        )

    def _convert_ir_mul_to_mul_ir(self, x: jnp.ndarray) -> jnp.ndarray:
        """Reorder ir_mul input layout to mul_ir."""
        segments: list[jnp.ndarray] = []
        offset = 0
        for mul_ir in self.irreps_in_cue_base:
            width = mul_ir.ir.dim
            seg = x[:, offset : offset + width, :]
            if seg.shape[1] != width:
                raise ValueError("Input feature dimension mismatch with irreps.")
            segments.append(jnp.swapaxes(seg, -1, -2))
            offset += width

        if offset != x.shape[1]:
            raise ValueError("Input feature dimension mismatch with irreps.")

        if not segments:
            return jnp.swapaxes(x, -1, -2)

        return jnp.concatenate(segments, axis=-1)


## Utilities
## ----------------------------------------------------------------------------


def _validate_features(x: jnp.ndarray, mul: int, feature_dim: int) -> None:
    """Ensure the feature tensor shape matches the expected mul_ir layout.

    Raises
    ------
    ValueError
        If ``x`` does not conform to ``(batch, mul, feature_dim)``.
    """
    if x.ndim != 3 or x.shape[1] != mul or x.shape[2] != feature_dim:
        raise ValueError(
            "SymmetricContraction expects input with shape "
            f"(batch, {mul}, {feature_dim}); got {tuple(x.shape)}"
        )


def _validate_features_ir_mul(x: jnp.ndarray, mul: int, feature_dim: int) -> None:
    """Ensure the feature tensor shape matches the expected ir_mul layout."""
    if x.ndim != 3 or x.shape[1] != feature_dim or x.shape[2] != mul:
        raise ValueError(
            "SymmetricContraction expects input with shape "
            f"(batch, {feature_dim}, {mul}); got {tuple(x.shape)}"
        )


def _select_weights(
    weight_flat: jnp.ndarray,
    selector: jnp.ndarray,
    *,
    dtype: jnp.dtype,
    num_elements: int,
) -> jnp.ndarray:
    """Select element weights by index or mixing matrix.

    Parameters
    ----------
    weight_flat:
        Weight tensor flattened to ``(num_elements, weight_dim)``.
    selector:
        Either integer indices of shape ``(batch,)`` or a mixing matrix
        ``(batch, num_elements)``.
    dtype:
        Target dtype for the selection.
    num_elements:
        Upper bound used to validate integer indices.

    Returns
    -------
    jnp.ndarray
        Per-example weights ready to be wrapped in a :class:`RepArray`.
    """
    selector = jnp.asarray(selector)
    if selector.ndim == 1:
        idx = selector.astype(jnp.int32)
        invalid = jnp.any(idx < 0) | jnp.any(idx >= num_elements)

        def _raise(_):
            jax.debug.callback(_raise_invalid_indices, jnp.int32(0))
            return jnp.int32(0)

        jax.lax.cond(invalid, _raise, lambda _: jnp.int32(0), operand=jnp.int32(0))
        return weight_flat[idx]

    if selector.ndim == 2:
        if selector.shape[1] != num_elements:
            raise ValueError("Mixing matrix must have second dimension num_elements")
        mix = jnp.asarray(selector, dtype=dtype)
        return mix @ weight_flat

    raise ValueError("indices must be rank-1 (element ids) or rank-2 (mixing matrix)")


def _raise_invalid_indices(_: jnp.ndarray) -> None:
    raise ValueError("indices out of range for the available elements")


def _symmetric_contraction_import_from_torch_with_layout(cls, torch_module, variables):
    """Wrapper around the auto-generated import that enforces layout parity."""
    expected_input = variables.get("input_layout_config", None)
    expected_output = variables.get("output_layout_config", None)

    def _decode_layout(val):
        if isinstance(val, jnp.ndarray):
            try:
                val_int = int(val)
            except Exception:
                return None
            return "mul_ir" if val_int == 0 else "ir_mul"
        if isinstance(val, (int, np.integer)):
            return "mul_ir" if int(val) == 0 else "ir_mul"
        return val

    def _layout_str_from_obj(layout_obj) -> str | None:
        if layout_obj is None:
            return None
        if isinstance(layout_obj, str):
            return layout_obj
        for attr in ("layout_str", "name", "__name__"):
            val = getattr(layout_obj, attr, None)
            if val is not None:
                return str(val)
        return str(layout_obj)

    expected_input = _decode_layout(expected_input)
    expected_output = _decode_layout(expected_output)

    torch_input = _layout_str_from_obj(getattr(torch_module, "input_layout", None))
    torch_output = _layout_str_from_obj(getattr(torch_module, "output_layout", None))
    if torch_input is None or torch_output is None:
        descriptor = getattr(torch_module, "descriptor", None) or getattr(
            torch_module, "_descriptor", None
        )
        if descriptor is not None:
            if torch_input is None:
                try:
                    torch_input = _layout_str_from_obj(descriptor.inputs[1].layout)
                except Exception:
                    torch_input = None
            if torch_output is None:
                try:
                    torch_output = _layout_str_from_obj(descriptor.outputs[0].layout)
                except Exception:
                    torch_output = None

    if torch_input is None:
        torch_input = "mul_ir"
    if torch_output is None:
        torch_output = "mul_ir"

    if expected_input is not None and str(expected_input) != str(torch_input):
        logging.warning(
            "JAX SymmetricContraction input layout %r differs from Torch layout %r; importing weights without conversion.",
            expected_input,
            torch_input,
        )
    if expected_output is not None and str(expected_output) != str(torch_output):
        logging.warning(
            "JAX SymmetricContraction output layout %r differs from Torch layout %r; importing weights without conversion.",
            expected_output,
            torch_output,
        )

    return cls._import_from_torch_impl(
        torch_module,
        variables,
        skip_root=False,
    )


# Override the auto-generated import_from_torch with layout validation.
SymmetricContraction.import_from_torch = classmethod(
    _symmetric_contraction_import_from_torch_with_layout
)


## Import functions
## ----------------------------------------------------------------------------


@nxx_register_import_mapper(
    "cuequivariance_torch.operations.symmetric_contraction.SymmetricContraction"
)
def _import_cue_symmetric_contraction(module, variables, scope) -> None:
    """Import mapper that transfers weights from the cuEquivariance Torch module.

    The Torch implementation stores its parameter as a dense tensor in the
    layout expected by cueEquivariance, so we only need to copy it over while
    preserving dtype.  The helper is registered so ``init_from_torch`` can reuse
    the logic automatically.
    """
    target = _resolve_scope(variables, scope)
    weight = module.weight.detach().cpu().numpy()
    existing = target.get("weight")
    dtype = existing.dtype if existing is not None else weight.dtype
    target["weight"] = jnp.asarray(weight, dtype=dtype)


@nxx_register_import_mapper("mace.modules.symmetric_contraction.SymmetricContraction")
def _import_native_symmetric_contraction(module, variables, scope) -> None:
    """Import mapper for native Torch MACE symmetric-contraction modules."""
    target = _resolve_scope(variables, scope)
    weight = target.get("weight")
    if weight is None:
        raise ValueError("Target JAX symmetric-contraction scope has no 'weight'.")

    target_template = jnp.asarray(weight, dtype=default_dtype())
    design_matrix_fn, target_basis_kind = _build_jax_target_design_matrix_fn(
        module,
        target_template=target_template,
        target_scope=target,
    )
    converted = convert_native_symmetric_weights(
        module,
        target_template=target_template,
        target_design_matrix_fn=design_matrix_fn,
        target_basis_kind=target_basis_kind,
    )
    target["weight"] = jnp.asarray(converted, dtype=weight.dtype)


def _decode_layout_config(value, default: str) -> str:
    """Decode stored integer/string layout metadata into a layout string."""
    if isinstance(value, jnp.ndarray):
        value = int(value)
    if isinstance(value, np.ndarray):
        value = int(value.reshape(()))
    if isinstance(value, (int, np.integer)):
        return "mul_ir" if int(value) == 0 else "ir_mul"
    if isinstance(value, str):
        return value
    return default


def _build_matching_jax_symmetric_contraction(
    torch_module,
    *,
    target_template: jnp.ndarray,
    target_scope: dict,
) -> tuple[nnx.GraphDef, dict, str]:
    """Construct a temporary JAX module that matches the target weight shape."""
    input_layout = _decode_layout_config(
        target_scope.get("input_layout_config"),
        "mul_ir",
    )
    output_layout = _decode_layout_config(
        target_scope.get("output_layout_config"),
        "mul_ir",
    )
    irreps_in = Irreps(str(torch_module.irreps_in))
    irreps_out = Irreps(str(torch_module.irreps_out))
    correlation = int(torch_module.contractions[0].correlation)
    basis_dim = int(np.asarray(target_template).shape[1])

    for use_reduced_cg in (True, False):
        module = SymmetricContraction(
            irreps_in=irreps_in,
            irreps_out=irreps_out,
            correlation=correlation,
            num_elements=1,
            use_reduced_cg=use_reduced_cg,
            input_layout=input_layout,
            output_layout=output_layout,
            rngs=nnx.Rngs(0),
        )
        graphdef, state = nnx.split(module)
        params = state_to_pure_dict(state)
        if int(np.asarray(params["weight"]).shape[1]) == basis_dim:
            target_basis_kind = "reduced" if use_reduced_cg else "canonical_full"
            return graphdef, _with_zero_weights(params), target_basis_kind

    raise ValueError(
        "Failed to match the target JAX symmetric-contraction basis shape."
    )


def _with_zero_weights(params: dict) -> dict:
    """Return a params pytree with all learnable weights zeroed."""
    params_mutable = dict(params)
    params_mutable["weight"] = jnp.zeros_like(params_mutable["weight"])
    return params_mutable


def _canonical_design_matrix(
    graphdef: nnx.GraphDef,
    params_zero: dict,
    inputs: jnp.ndarray,
    indices: jnp.ndarray,
) -> np.ndarray:
    """Evaluate the temporary JAX module on all target basis vectors."""
    weight_shape = np.asarray(params_zero["weight"]).shape
    basis_dim = int(weight_shape[1])

    outputs: list[np.ndarray] = []
    for idx in range(basis_dim):
        weight = np.zeros(weight_shape, dtype=np.float32)
        weight[0, idx, 0] = 1.0

        params_idx = dict(params_zero)
        params_idx["weight"] = jnp.asarray(weight)
        out, _ = graphdef.apply(params_idx)(inputs, indices)
        outputs.append(np.asarray(out).reshape(-1))

    return np.stack(outputs, axis=1)


def _build_jax_target_design_matrix_fn(
    torch_module,
    *,
    target_template: jnp.ndarray,
    target_scope: dict,
):
    """Build the JAX-side design-matrix callback for native weight conversion."""
    graphdef, params_zero, target_basis_kind = _build_matching_jax_symmetric_contraction(
        torch_module,
        target_template=target_template,
        target_scope=target_scope,
    )

    def _design_matrix(basis_dim: int, inputs_np: np.ndarray) -> np.ndarray:
        if int(np.asarray(params_zero["weight"]).shape[1]) != basis_dim:
            raise ValueError("Target JAX basis dimension mismatch during import.")
        inputs = jnp.asarray(inputs_np)
        indices = jnp.zeros((inputs_np.shape[0],), dtype=jnp.int32)
        return _canonical_design_matrix(graphdef, params_zero, inputs, indices)

    return _design_matrix, target_basis_kind
